kind: pipeline
type: docker
name: default

when:
  event:
    - push

steps:
  hello:
    image: python:3.12
    commands:
      - echo "✅ Woodpecker pipeline triggered automatically by PUSH"
      - python3 --version
